#!/usr/bin/env bash
set -euo pipefail
set +x
umask 077

# Configuration never accepts R2 credentials from the environment. Clear them
# before any helper or tool process runs so only Keychain can supply the pair.
unset CLOUDFLARE_R2_ACCESS_KEY_ID CLOUDFLARE_R2_SECRET_ACCESS_KEY

usage() {
  cat <<'EOF'
Usage:
  release-configure.sh [--config FILE] [--force] [--skip-r2-credentials] [--skip-r2-check]

Interactively configures this Mac for DuckGooKey public releases.

Writes only non-secret Apple and R2 settings to an ignored mise.local.toml.
R2 credentials are prompted by macOS security and stored in the default user
Keychain. Existing shell environment values remain one-run overrides because
the generated mise values use Mise's { default = ... } form.

Options:
  --config FILE             Write a different local Mise file (project-relative)
  --force                   Replace an existing unmanaged config file
  --skip-r2-credentials     Do not inspect or update R2 Keychain credentials
  --skip-r2-check           Do not check the R2 bucket after Keychain setup
  --help, -h                Show this help
EOF
}

die() {
  printf 'release-configure: %s\n' "$*" >&2
  exit 1
}

usage_error() {
  printf 'release-configure: %s\n' "$*" >&2
  usage >&2
  exit 2
}

prompt_value() {
  local output_variable="$1"
  local label="$2"
  local default_value="$3"
  local value=""

  if [[ -n "$default_value" ]]; then
    printf '%s [%s]: ' "$label" "$default_value" >&2
  else
    printf '%s: ' "$label" >&2
  fi
  IFS= read -r value || die "input ended before $label was provided"
  if [[ -z "$value" ]]; then
    value="$default_value"
  fi
  printf -v "$output_variable" '%s' "$value"
}

prompt_yes_no() {
  local output_variable="$1"
  local label="$2"
  local default_value="$3"
  local value=""
  local suffix="[y/N]"

  if [[ "$default_value" == "yes" ]]; then
    suffix="[Y/n]"
  fi
  while true; do
    printf '%s %s: ' "$label" "$suffix" >&2
    IFS= read -r value || die "input ended before answering: $label"
    if [[ -z "$value" ]]; then
      value="$default_value"
    fi
    case "$value" in
      y|Y|yes|YES)
        printf -v "$output_variable" '%s' "yes"
        return
        ;;
      n|N|no|NO)
        printf -v "$output_variable" '%s' "no"
        return
        ;;
      *)
        printf 'Please answer yes or no.\n' >&2
        ;;
    esac
  done
}

validate_team_id() {
  [[ "$1" =~ ^[A-Z0-9]{10}$ ]]
}

validate_bucket() {
  [[ "$1" =~ ^[a-z0-9][a-z0-9-]{1,61}[a-z0-9]$ ]]
}

validate_r2_endpoint() {
  [[ "$1" =~ ^https://[A-Za-z0-9.-]+\.r2\.cloudflarestorage\.com$ ]]
}

validate_base_url() {
  [[ "$1" =~ ^https://[^/?#[:space:]]+([^?#[:space:]]*)?$ ]]
}

write_config() {
  local output_path="$1"
  local signing_identity="$2"
  local team_id="$3"
  local notary_profile="$4"
  local bucket="$5"
  local endpoint="$6"
  local public_base_url="$7"

  python3 - \
    "$output_path" \
    "$signing_identity" \
    "$team_id" \
    "$notary_profile" \
    "$bucket" \
    "$endpoint" \
    "$public_base_url" <<'PY'
import json
import pathlib
import sys

output = pathlib.Path(sys.argv[1])
entries = [
    ("APPLE_SIGNING_IDENTITY", sys.argv[2]),
    ("APPLE_TEAM_ID", sys.argv[3]),
    ("APPLE_KEYCHAIN_PROFILE", sys.argv[4]),
    ("CLOUDFLARE_R2_BUCKET", sys.argv[5]),
    ("CLOUDFLARE_R2_ENDPOINT", sys.argv[6]),
    ("CLOUDFLARE_R2_PUBLIC_BASE_URL", sys.argv[7]),
]

lines = [
    "# Generated by scripts/release-configure.sh.",
    "# This file contains non-secret machine-local release settings.",
    "# R2 credentials are stored in the macOS Keychain, never here.",
    "",
    "[env]",
]
for key, value in entries:
    lines.append(f"{key} = {{ default = {json.dumps(value, ensure_ascii=False)} }}")
output.write_text("\n".join(lines) + "\n", encoding="utf-8")
PY
}

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
project_dir="$(cd "$script_dir/.." && pwd)"
# shellcheck source=release-keychain.sh
source "$script_dir/release-keychain.sh"

config_path="$project_dir/mise.local.toml"
force="false"
skip_r2_credentials="false"
skip_r2_check="false"

while (( $# > 0 )); do
  case "$1" in
    --config)
      [[ -n "${2-}" ]] || usage_error "--config requires a non-empty value"
      config_path="$2"
      shift 2
      ;;
    --force)
      force="true"
      shift
      ;;
    --skip-r2-credentials)
      skip_r2_credentials="true"
      shift
      ;;
    --skip-r2-check)
      skip_r2_check="true"
      shift
      ;;
    --help|-h)
      usage
      exit 0
      ;;
    *)
      usage_error "unknown argument: $1"
      ;;
  esac
done

if [[ "$config_path" != /* ]]; then
  config_path="$project_dir/$config_path"
fi

[[ "$(uname -s)" == "Darwin" ]] || die "local release configuration is supported only on macOS"
command -v security >/dev/null 2>&1 || die "macOS security CLI is required"
command -v mise >/dev/null 2>&1 || die "mise is required; install it and run mise install --locked"
command -v python3 >/dev/null 2>&1 || die "python3 is required"

config_directory="$(dirname "$config_path")"
mkdir -p "$config_directory"
if [[ -L "$config_path" ]]; then
  die "refusing to replace a symbolic-link config file: $config_path"
fi
if [[ -e "$config_path" ]] \
  && ! grep -qF '# Generated by scripts/release-configure.sh.' "$config_path" \
  && [[ "$force" != "true" ]]; then
  die "refusing to replace unmanaged config $config_path; use --force after reviewing it"
fi

identities="$(security find-identity -v -p codesigning 2>/dev/null || true)"
default_signing_identity="${APPLE_SIGNING_IDENTITY:-}"
if [[ -z "$default_signing_identity" ]]; then
  default_signing_identity="$(
    printf '%s\n' "$identities" \
      | sed -n 's/.*"\(Developer ID Application:.*\)"/\1/p' \
      | head -n 1
  )"
fi
default_team_id="${APPLE_TEAM_ID:-}"
if [[ -z "$default_team_id" && "$default_signing_identity" =~ \(([A-Z0-9]{10})\)$ ]]; then
  default_team_id="${BASH_REMATCH[1]}"
fi

signing_identity=""
team_id=""
notary_profile=""
r2_bucket=""
r2_endpoint=""
public_base_url=""
prompt_value signing_identity "Developer ID Application identity" "$default_signing_identity"
prompt_value team_id "Apple Developer Team ID" "$default_team_id"
prompt_value notary_profile "notarytool Keychain profile" "${APPLE_KEYCHAIN_PROFILE:-duckgookey-notary}"
prompt_value r2_bucket "Cloudflare R2 bucket" "${CLOUDFLARE_R2_BUCKET:-duckgoo-key-releases}"
prompt_value r2_endpoint "Cloudflare R2 S3 endpoint" "${CLOUDFLARE_R2_ENDPOINT:-}"
prompt_value public_base_url "Public update base URL" "${CLOUDFLARE_R2_PUBLIC_BASE_URL:-https://updates.key.duckgoo.net}"

[[ "$signing_identity" == "Developer ID Application: "* ]] \
  || die "Apple signing identity must begin with Developer ID Application:"
validate_team_id "$team_id" || die "Apple Developer Team ID must be 10 uppercase letters or digits"
[[ "$signing_identity" == *" ($team_id)" ]] \
  || die "Apple signing identity must end with the selected Team ID"
printf '%s\n' "$identities" | grep -F -- "\"$signing_identity\"" >/dev/null \
  || printf 'release-configure: warning: could not confirm the selected Developer ID identity in this task shell; release packaging will verify it before distribution.\n' >&2
[[ -n "$notary_profile" ]] || die "notarytool Keychain profile must not be empty"
validate_bucket "$r2_bucket" || die "R2 bucket must be 3-63 lowercase letters, digits, or hyphens"
validate_r2_endpoint "$r2_endpoint" \
  || die "R2 endpoint must be https://ACCOUNT_ID.r2.cloudflarestorage.com without a path"
validate_base_url "$public_base_url" \
  || die "public update base URL must be HTTPS without a query or fragment"
while [[ "$public_base_url" == */ ]]; do
  public_base_url="${public_base_url%/}"
done

temporary_config="$(mktemp "$config_directory/.mise.local.toml.XXXXXX")"
new_access_key_needs_cleanup="false"
cleanup() {
  if [[ -n "${temporary_config:-}" && -f "$temporary_config" ]]; then
    rm -f "$temporary_config"
  fi
  if [[ "${new_access_key_needs_cleanup:-false}" == "true" ]]; then
    duckgookey_delete_r2_keychain_item "$DUCKGOOKEY_R2_ACCESS_KEY_ACCOUNT" || true
  fi
}
trap cleanup EXIT

write_config \
  "$temporary_config" \
  "$signing_identity" \
  "$team_id" \
  "$notary_profile" \
  "$r2_bucket" \
  "$r2_endpoint" \
  "$public_base_url"
chmod 600 "$temporary_config"

r2_credentials_ready="false"
r2_credential_status="not configured"
if [[ "$skip_r2_credentials" != "true" ]]; then
  duckgookey_resolve_default_user_keychain \
    || die "$DUCKGOOKEY_R2_CREDENTIAL_ERROR"

  access_key_exists="false"
  secret_key_exists="false"
  if duckgookey_r2_keychain_item_exists "$DUCKGOOKEY_R2_ACCESS_KEY_ACCOUNT"; then
    access_key_exists="true"
  fi
  if duckgookey_r2_keychain_item_exists "$DUCKGOOKEY_R2_SECRET_KEY_ACCOUNT"; then
    secret_key_exists="true"
  fi

  replace_credentials="no"
  if [[ "$access_key_exists" == "true" && "$secret_key_exists" == "true" ]]; then
    prompt_yes_no replace_credentials "Replace existing R2 Keychain credentials" "no"
  elif [[ "$access_key_exists" == "false" && "$secret_key_exists" == "false" ]]; then
    prompt_yes_no replace_credentials "Store R2 credentials in the default user Keychain" "yes"
  else
    printf 'R2 Keychain credentials are incomplete; both entries must be replaced together.\n' >&2
    prompt_yes_no replace_credentials "Replace the incomplete R2 Keychain credential pair" "yes"
    [[ "$replace_credentials" == "yes" ]] \
      || die "R2 Keychain credentials are incomplete; rerun and replace both entries"
  fi

  if [[ "$replace_credentials" == "yes" ]]; then
    printf 'Enter the R2 access key ID in the secure macOS Keychain prompt.\n' >&2
    if ! duckgookey_store_r2_keychain_item \
      "$DUCKGOOKEY_R2_ACCESS_KEY_ACCOUNT" \
      "DuckGooKey R2 access key ID"; then
      die "could not store the R2 access key ID in Keychain"
    fi
    if [[ "$access_key_exists" == "false" ]]; then
      new_access_key_needs_cleanup="true"
    fi
    printf 'Enter the R2 secret access key in the secure macOS Keychain prompt.\n' >&2
    if ! duckgookey_store_r2_keychain_item \
      "$DUCKGOOKEY_R2_SECRET_KEY_ACCOUNT" \
      "DuckGooKey R2 secret access key"; then
      die "could not store the R2 secret access key in Keychain"
    fi
    new_access_key_needs_cleanup="false"
    r2_credential_status="updated in Keychain"
  elif [[ "$access_key_exists" == "true" && "$secret_key_exists" == "true" ]]; then
    r2_credential_status="kept in Keychain"
  fi

  if [[ "$replace_credentials" == "yes" ]] \
    || [[ "$access_key_exists" == "true" && "$secret_key_exists" == "true" ]]; then
    r2_credentials_ready="true"
  fi
fi

if [[ "$r2_credentials_ready" == "true" && "$skip_r2_check" != "true" ]]; then
  if ! duckgookey_read_r2_keychain_credentials; then
    die "$DUCKGOOKEY_R2_CREDENTIAL_ERROR"
  fi
  printf 'Checking R2 bucket access...\n'
  mise install --locked aws
  if ! AWS_ACCESS_KEY_ID="$DUCKGOOKEY_RESOLVED_R2_ACCESS_KEY_ID" \
    AWS_SECRET_ACCESS_KEY="$DUCKGOOKEY_RESOLVED_R2_SECRET_ACCESS_KEY" \
    AWS_DEFAULT_REGION=auto \
    AWS_EC2_METADATA_DISABLED=true \
    MISE_AUTO_INSTALL=false MISE_EXEC_AUTO_INSTALL=false \
      mise exec -- aws \
        --endpoint-url "$r2_endpoint" \
        --no-cli-pager \
        s3api list-objects-v2 \
        --bucket "$r2_bucket" \
        --max-keys 1 \
        --output json >/dev/null; then
    DUCKGOOKEY_RESOLVED_R2_ACCESS_KEY_ID=""
    DUCKGOOKEY_RESOLVED_R2_SECRET_ACCESS_KEY=""
    die "R2 bucket access check failed; the Keychain values were kept so you can correct them and rerun"
  fi
  DUCKGOOKEY_RESOLVED_R2_ACCESS_KEY_ID=""
  DUCKGOOKEY_RESOLVED_R2_SECRET_ACCESS_KEY=""
fi

mv "$temporary_config" "$config_path"
temporary_config=""
if ! mise trust --yes "$config_path"; then
  die "configuration was written but mise could not trust it; run mise trust $config_path"
fi

printf '\nLocal release configuration is ready:\n'
printf '  Mise settings: %s\n' "$config_path"
printf '  R2 credentials: %s\n' "$r2_credential_status"
printf '  Notary profile: %s\n' "$notary_profile"
printf '\nIf the notary profile does not exist yet, run xcrun notarytool store-credentials %s.\n' \
  "$notary_profile"
