use std::borrow::Cow;
use std::cmp::Ordering as CmpOrdering;
use std::collections::{BTreeMap, HashSet};
use std::ffi::c_void;
use std::fs::{self, File, OpenOptions};
use std::io::{self, BufRead, BufReader, Write};
use std::os::unix::ffi::OsStringExt;
use std::path::{Component, Path, PathBuf};
use std::process::{Command, Stdio};
use std::sync::atomic::{AtomicU64, Ordering};
use std::sync::mpsc;
use std::thread;
use std::time::{Duration, SystemTime, UNIX_EPOCH};

use core_foundation::array::{CFArray, CFArrayRef};
use core_foundation::base::{Boolean, CFType, TCFType};
use core_foundation::boolean::CFBoolean;
use core_foundation::dictionary::{CFDictionary, CFDictionaryRef};
use core_foundation::string::{CFString, CFStringRef};
use directories::UserDirs;
use objc2_app_kit::{NSPasteboard, NSPasteboardTypeString};
use objc2_foundation::NSString;
use plist::{Dictionary, Value};
use walkdir::WalkDir;

use crate::START_HIDDEN_ARGUMENT;
use crate::catalog::{CatalogItem, LaunchAction};
use crate::commands::SystemCommand;

use super::{ClipboardSnapshot, InputSource, PlatformError, Result};

const OPEN_EXECUTABLE: &str = "/usr/bin/open";
const MDFIND_EXECUTABLE: &str = "/usr/bin/mdfind";
const OSASCRIPT_EXECUTABLE: &str = "/usr/bin/osascript";
const PMSET_EXECUTABLE: &str = "/usr/bin/pmset";
const LAUNCH_AGENT_LABEL: &str = "com.duckgoo.key";
const LAUNCH_AGENT_FILE_NAME: &str = "com.duckgoo.key.plist";
const FILE_SEARCH_TIMEOUT: Duration = Duration::from_secs(5);
const IGNORED_PASTEBOARD_TYPES: [&str; 8] = [
    "org.nspasteboard.TransientType",
    "org.nspasteboard.ConcealedType",
    "org.nspasteboard.AutoGeneratedType",
    "com.agilebits.onepassword",
    "net.antelle.keeweb",
    "com.typeit4me.clipping",
    "de.petermaurer.TransientPasteboardType",
    "Pasteboard generator type",
];
static TEMP_FILE_COUNTER: AtomicU64 = AtomicU64::new(0);

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
struct SystemCommandSpec {
    executable: &'static str,
    arguments: &'static [&'static str],
    operation: &'static str,
}

type TISInputSourceRef = *const c_void;
type OSStatus = i32;

const NO_ERR: OSStatus = 0;
const INPUT_SOURCE_IDENTIFIER_PROPERTY: &str = "input source identifier";
const LOCALIZED_NAME_PROPERTY: &str = "localized name";

#[allow(non_upper_case_globals)]
#[link(name = "Carbon", kind = "framework")]
unsafe extern "C" {
    static kTISCategoryKeyboardInputSource: CFStringRef;
    static kTISPropertyInputSourceCategory: CFStringRef;
    static kTISPropertyInputSourceID: CFStringRef;
    static kTISPropertyInputSourceIsEnabled: CFStringRef;
    static kTISPropertyInputSourceIsSelectCapable: CFStringRef;
    static kTISPropertyLocalizedName: CFStringRef;

    fn TISCopyCurrentKeyboardInputSource() -> TISInputSourceRef;
    fn TISCreateInputSourceList(
        properties: CFDictionaryRef,
        include_all_installed: Boolean,
    ) -> CFArrayRef;
    fn TISGetInputSourceProperty(
        input_source: TISInputSourceRef,
        property_key: CFStringRef,
    ) -> *const c_void;
    fn TISSelectInputSource(input_source: TISInputSourceRef) -> OSStatus;
}

pub fn discover_applications() -> Result<Vec<CatalogItem>> {
    let home_directory = UserDirs::new().map(|directories| directories.home_dir().to_owned());
    Ok(discover_in_roots(&application_roots(
        home_directory.as_deref(),
    )))
}

fn application_roots(home_directory: Option<&Path>) -> Vec<PathBuf> {
    let mut roots = vec![
        PathBuf::from("/Applications"),
        PathBuf::from("/System/Applications"),
        PathBuf::from("/System/Library/CoreServices/Applications"),
        PathBuf::from("/System/Library/CoreServices/Finder.app"),
    ];
    if let Some(home_directory) = home_directory {
        roots.push(home_directory.join("Applications"));
    }
    roots
}

pub fn launch(action: &LaunchAction) -> Result<()> {
    let mut command = Command::new(OPEN_EXECUTABLE);
    let error_path = match action {
        LaunchAction::OpenApplication { path } | LaunchAction::OpenPath { path } => {
            // `open` accepts `--` even though it is omitted from its help text.
            // Terminating option parsing keeps unusual relative paths from
            // being interpreted as launcher flags.
            command.arg("--").arg(path);
            path.clone()
        }
        LaunchAction::OpenUrl { url } => {
            // `-u` makes the following argument unambiguously a URL, even if
            // malformed persisted input begins with an option-like prefix.
            command.arg("-u").arg(url);
            PathBuf::from(url)
        }
        LaunchAction::CopyText { .. } => {
            return Err(PlatformError::UnsupportedAction {
                action: "copy text",
            });
        }
        LaunchAction::SystemCommand { .. } => {
            return Err(PlatformError::UnsupportedAction {
                action: "system command",
            });
        }
        LaunchAction::EnterSearchMode { .. } => {
            return Err(PlatformError::UnsupportedAction {
                action: "enter search mode",
            });
        }
        LaunchAction::ManageQuickLinks => {
            return Err(PlatformError::UnsupportedAction {
                action: "manage quick links",
            });
        }
        LaunchAction::RefreshCatalog => {
            return Err(PlatformError::UnsupportedAction {
                action: "refresh catalog",
            });
        }
        LaunchAction::Quit => {
            return Err(PlatformError::UnsupportedAction { action: "quit" });
        }
    };

    let status = command.status().map_err(|source| PlatformError::Io {
        operation: "launching an item",
        path: error_path,
        source,
    })?;
    if status.success() {
        Ok(())
    } else {
        Err(PlatformError::CommandFailed {
            executable: OPEN_EXECUTABLE,
            status: status.code(),
        })
    }
}

pub fn reveal_in_file_manager(path: &Path) -> Result<()> {
    let status = Command::new(OPEN_EXECUTABLE)
        .arg("-R")
        .arg("--")
        .arg(path)
        .status()
        .map_err(|source| PlatformError::Io {
            operation: "revealing an item in Finder",
            path: path.to_owned(),
            source,
        })?;
    if status.success() {
        Ok(())
    } else {
        Err(PlatformError::CommandFailed {
            executable: OPEN_EXECUTABLE,
            status: status.code(),
        })
    }
}

pub fn execute_system_command(command: &SystemCommand) -> Result<()> {
    let spec = system_command_spec(command);
    let status = Command::new(spec.executable)
        .args(spec.arguments)
        .status()
        .map_err(|source| PlatformError::Io {
            operation: spec.operation,
            path: PathBuf::from(spec.executable),
            source,
        })?;
    if status.success() {
        Ok(())
    } else {
        Err(PlatformError::CommandFailed {
            executable: spec.executable,
            status: status.code(),
        })
    }
}

fn system_command_spec(command: &SystemCommand) -> SystemCommandSpec {
    match command {
        SystemCommand::OpenSystemSettings => SystemCommandSpec {
            executable: OPEN_EXECUTABLE,
            arguments: &["-b", "com.apple.systempreferences"],
            operation: "opening System Settings",
        },
        SystemCommand::Sleep => SystemCommandSpec {
            executable: PMSET_EXECUTABLE,
            arguments: &["sleepnow"],
            operation: "putting the Mac to sleep",
        },
        SystemCommand::LockScreen => SystemCommandSpec {
            executable: OSASCRIPT_EXECUTABLE,
            arguments: &[
                "-e",
                "tell application \"System Events\" to keystroke \"q\" using {control down, command down}",
            ],
            operation: "locking the screen",
        },
        SystemCommand::ToggleAppearance => SystemCommandSpec {
            executable: OSASCRIPT_EXECUTABLE,
            arguments: &[
                "-e",
                "tell application \"System Events\" to tell appearance preferences to set dark mode to not dark mode",
            ],
            operation: "toggling the system appearance",
        },
        SystemCommand::EmptyTrash => SystemCommandSpec {
            executable: OSASCRIPT_EXECUTABLE,
            arguments: &["-e", "tell application \"Finder\" to empty trash"],
            operation: "emptying the Trash",
        },
        SystemCommand::LogOut => SystemCommandSpec {
            executable: OSASCRIPT_EXECUTABLE,
            arguments: &["-e", "tell application \"System Events\" to log out"],
            operation: "logging out",
        },
        SystemCommand::Restart => SystemCommandSpec {
            executable: OSASCRIPT_EXECUTABLE,
            arguments: &["-e", "tell application \"System Events\" to restart"],
            operation: "restarting the Mac",
        },
        SystemCommand::ShutDown => SystemCommandSpec {
            executable: OSASCRIPT_EXECUTABLE,
            arguments: &["-e", "tell application \"System Events\" to shut down"],
            operation: "shutting down the Mac",
        },
    }
}

pub fn search_files(query: &str, limit: usize) -> Result<Vec<PathBuf>> {
    let query = query.trim();
    if query.is_empty() || limit == 0 {
        return Ok(Vec::new());
    }
    let query = mdfind_name_query(query);

    let user_directories = UserDirs::new().ok_or(PlatformError::HomeDirectoryUnavailable)?;
    let home_directory = user_directories.home_dir();
    let mut child = Command::new(MDFIND_EXECUTABLE)
        .arg("-0")
        .arg("-onlyin")
        .arg(home_directory)
        .arg("-name")
        .arg(query.as_ref())
        .stdout(Stdio::piped())
        .stderr(Stdio::null())
        .spawn()
        .map_err(|source| PlatformError::Io {
            operation: "starting Spotlight file search",
            path: PathBuf::from(MDFIND_EXECUTABLE),
            source,
        })?;

    let Some(stdout) = child.stdout.take() else {
        let _ = child.kill();
        let _ = child.wait();
        return Err(PlatformError::Io {
            operation: "reading Spotlight file search results",
            path: PathBuf::from(MDFIND_EXECUTABLE),
            source: io::Error::new(io::ErrorKind::BrokenPipe, "mdfind stdout was unavailable"),
        });
    };
    let (sender, receiver) = mpsc::sync_channel(1);
    let reader = thread::spawn(move || {
        let _ = sender.send(read_nul_separated_paths(BufReader::new(stdout), limit));
    });
    let paths = match receiver.recv_timeout(FILE_SEARCH_TIMEOUT) {
        Ok(Ok(paths)) => paths,
        Ok(Err(source)) => {
            let _ = child.kill();
            let _ = child.wait();
            let _ = reader.join();
            return Err(PlatformError::Io {
                operation: "reading Spotlight file search results",
                path: PathBuf::from(MDFIND_EXECUTABLE),
                source,
            });
        }
        Err(mpsc::RecvTimeoutError::Timeout) => {
            let _ = child.kill();
            let _ = child.wait();
            let _ = reader.join();
            return Err(PlatformError::CommandTimedOut {
                executable: MDFIND_EXECUTABLE,
                timeout_ms: u64::try_from(FILE_SEARCH_TIMEOUT.as_millis()).unwrap_or(u64::MAX),
            });
        }
        Err(mpsc::RecvTimeoutError::Disconnected) => {
            let _ = child.kill();
            let _ = child.wait();
            let _ = reader.join();
            return Err(PlatformError::Io {
                operation: "reading Spotlight file search results",
                path: PathBuf::from(MDFIND_EXECUTABLE),
                source: io::Error::other("Spotlight result reader stopped unexpectedly"),
            });
        }
    };
    let _ = reader.join();

    if paths.len() == limit {
        // `mdfind` has no result-limit flag. Stop it as soon as enough paths
        // have been read so a broad query cannot grow memory without bound.
        let _ = child.kill();
        let _ = child.wait();
        return Ok(paths);
    }

    let status = child.wait().map_err(|source| PlatformError::Io {
        operation: "waiting for Spotlight file search",
        path: PathBuf::from(MDFIND_EXECUTABLE),
        source,
    })?;
    if status.success() {
        Ok(paths)
    } else {
        Err(PlatformError::CommandFailed {
            executable: MDFIND_EXECUTABLE,
            status: status.code(),
        })
    }
}

fn mdfind_name_query(query: &str) -> Cow<'_, str> {
    if query.starts_with('-') {
        // Unlike most command-line tools, `mdfind` does not accept `--` and
        // interprets even the value following `-name` as an option. A leading
        // wildcard preserves filename matching while preventing option
        // parsing for names such as `-notes`.
        Cow::Owned(format!("*{query}"))
    } else {
        Cow::Borrowed(query)
    }
}

fn read_nul_separated_paths(mut reader: impl BufRead, limit: usize) -> io::Result<Vec<PathBuf>> {
    let mut paths = Vec::with_capacity(limit.min(64));
    let mut encoded_path = Vec::new();
    while paths.len() < limit {
        encoded_path.clear();
        if reader.read_until(0, &mut encoded_path)? == 0 {
            break;
        }
        if encoded_path.last() == Some(&0) {
            encoded_path.pop();
        }
        if encoded_path.is_empty() {
            continue;
        }
        paths.push(PathBuf::from(std::ffi::OsString::from_vec(
            encoded_path.clone(),
        )));
    }
    Ok(paths)
}

pub fn clipboard_change_count() -> Result<i64> {
    Ok(NSPasteboard::generalPasteboard().changeCount() as i64)
}

pub fn read_clipboard_text_if_changed(previous: i64) -> Result<ClipboardSnapshot> {
    let pasteboard = NSPasteboard::generalPasteboard();
    let change_count = pasteboard.changeCount() as i64;
    if change_count == previous {
        return Ok(ClipboardSnapshot {
            change_count,
            text: None,
        });
    }

    if pasteboard_contains_ignored_type(&pasteboard) {
        let stable = pasteboard.changeCount() as i64 == change_count;
        return Ok(ClipboardSnapshot {
            change_count: if stable { change_count } else { previous },
            text: None,
        });
    }

    // SAFETY: `NSPasteboardTypeString` is a process-lifetime AppKit constant.
    let text = pasteboard
        .stringForType(unsafe { NSPasteboardTypeString })
        .map(|value| value.to_string());
    if pasteboard.changeCount() as i64 != change_count {
        // Do not pair text with a change count from a different clipboard
        // value. Keeping the caller's count makes the next poll retry.
        return Ok(ClipboardSnapshot {
            change_count: previous,
            text: None,
        });
    }

    Ok(ClipboardSnapshot { change_count, text })
}

fn pasteboard_contains_ignored_type(pasteboard: &NSPasteboard) -> bool {
    pasteboard.types().is_some_and(|types| {
        (0..types.count()).any(|index| {
            let data_type = types.objectAtIndex(index);
            is_ignored_pasteboard_type(&data_type.to_string())
        })
    })
}

fn is_ignored_pasteboard_type(data_type: &str) -> bool {
    IGNORED_PASTEBOARD_TYPES.contains(&data_type)
}

pub fn copy_text(text: &str) -> Result<i64> {
    let pasteboard = NSPasteboard::generalPasteboard();
    let value = NSString::from_str(text);
    pasteboard.clearContents();
    // SAFETY: `NSPasteboardTypeString` is a process-lifetime AppKit constant.
    if !pasteboard.setString_forType(&value, unsafe { NSPasteboardTypeString }) {
        return Err(PlatformError::ClipboardOperationRejected { operation: "write" });
    }
    Ok(pasteboard.changeCount() as i64)
}

pub fn launch_at_login_enabled() -> bool {
    let Some(path) = launch_agent_path() else {
        return false;
    };
    let Ok(executable) = std::env::current_exe() else {
        return false;
    };
    launch_at_login_enabled_at(&path, &executable)
}

pub fn set_launch_at_login(enabled: bool) -> Result<()> {
    let path = launch_agent_path().ok_or(PlatformError::HomeDirectoryUnavailable)?;
    if enabled {
        let executable = std::env::current_exe().map_err(PlatformError::CurrentExecutable)?;
        write_launch_agent(&path, &executable)
    } else {
        remove_launch_agent(&path)
    }
}

pub fn available_input_sources() -> Result<Vec<InputSource>> {
    let input_sources = selectable_keyboard_input_sources()?;
    let mut values = Vec::with_capacity(input_sources.len() as usize);

    for input_source in input_sources.get_all_values() {
        let identifier = required_string_property(
            input_source,
            unsafe { kTISPropertyInputSourceID },
            INPUT_SOURCE_IDENTIFIER_PROPERTY,
        )?;
        let localized_name = optional_string_property(
            input_source,
            unsafe { kTISPropertyLocalizedName },
            LOCALIZED_NAME_PROPERTY,
        )?
        .filter(|name| !name.trim().is_empty())
        .unwrap_or_else(|| identifier.clone());
        values.push(InputSource {
            identifier,
            localized_name,
        });
    }

    Ok(normalize_input_sources(values))
}

pub fn current_input_source_identifier() -> Result<String> {
    let input_source = unsafe { TISCopyCurrentKeyboardInputSource() };
    if input_source.is_null() {
        return Err(PlatformError::CurrentInputSourceUnavailable);
    }

    // `TISCopy…` follows the Create Rule, so this owner must release the source.
    let _input_source_owner = unsafe { CFType::wrap_under_create_rule(input_source) };
    required_string_property(
        input_source,
        unsafe { kTISPropertyInputSourceID },
        INPUT_SOURCE_IDENTIFIER_PROPERTY,
    )
}

pub fn select_input_source(identifier: &str) -> Result<()> {
    let input_sources = selectable_keyboard_input_sources()?;
    for input_source in input_sources.get_all_values() {
        let candidate_identifier = required_string_property(
            input_source,
            unsafe { kTISPropertyInputSourceID },
            INPUT_SOURCE_IDENTIFIER_PROPERTY,
        )?;
        if candidate_identifier != identifier {
            continue;
        }

        let status = unsafe { TISSelectInputSource(input_source) };
        return if status == NO_ERR {
            Ok(())
        } else {
            Err(PlatformError::InputSourceSelectionFailed {
                identifier: identifier.to_owned(),
                status,
            })
        };
    }

    Err(PlatformError::InputSourceUnavailable {
        identifier: identifier.to_owned(),
    })
}

fn selectable_keyboard_input_sources() -> Result<CFArray> {
    let properties = unsafe {
        // Framework constants follow the Get Rule. The wrappers retain them while the
        // dictionary is assembled, and the dictionary then retains its keys and values.
        let category_key = CFString::wrap_under_get_rule(kTISPropertyInputSourceCategory);
        let enabled_key = CFString::wrap_under_get_rule(kTISPropertyInputSourceIsEnabled);
        let select_capable_key =
            CFString::wrap_under_get_rule(kTISPropertyInputSourceIsSelectCapable);
        let keyboard_category =
            CFString::wrap_under_get_rule(kTISCategoryKeyboardInputSource).into_CFType();
        let true_value = CFBoolean::true_value().into_CFType();

        CFDictionary::from_CFType_pairs(&[
            (category_key, keyboard_category),
            (enabled_key, true_value.clone()),
            (select_capable_key, true_value),
        ])
    };

    let input_sources =
        unsafe { TISCreateInputSourceList(properties.as_concrete_TypeRef(), false as Boolean) };
    if input_sources.is_null() {
        Err(PlatformError::InputSourceListUnavailable)
    } else {
        // `TISCreate…` follows the Create Rule; CFArray releases this snapshot on drop.
        Ok(unsafe { CFArray::wrap_under_create_rule(input_sources) })
    }
}

fn required_string_property(
    input_source: TISInputSourceRef,
    property_key: CFStringRef,
    property: &'static str,
) -> Result<String> {
    match optional_string_property(input_source, property_key, property)? {
        Some(value) if !value.is_empty() => Ok(value),
        Some(_) => Err(PlatformError::InputSourcePropertyEmpty { property }),
        None => Err(PlatformError::InputSourcePropertyMissing { property }),
    }
}

fn optional_string_property(
    input_source: TISInputSourceRef,
    property_key: CFStringRef,
    property: &'static str,
) -> Result<Option<String>> {
    let value = unsafe { TISGetInputSourceProperty(input_source, property_key) };
    if value.is_null() {
        return Ok(None);
    }

    // TIS properties follow the Get Rule, so retain the borrowed value before wrapping it.
    let value = unsafe { CFType::wrap_under_get_rule(value) };
    value
        .downcast::<CFString>()
        .map(|value| Some(value.to_string()))
        .ok_or(PlatformError::InputSourcePropertyTypeMismatch { property })
}

fn normalize_input_sources(input_sources: Vec<InputSource>) -> Vec<InputSource> {
    let mut by_identifier = BTreeMap::<String, InputSource>::new();
    for input_source in input_sources {
        by_identifier
            .entry(input_source.identifier.clone())
            .and_modify(|existing| {
                if localized_name_order(&input_source, existing).is_lt() {
                    existing.localized_name = input_source.localized_name.clone();
                }
            })
            .or_insert(input_source);
    }

    let mut input_sources = by_identifier.into_values().collect::<Vec<_>>();
    input_sources.sort_by(localized_name_order);
    input_sources
}

fn localized_name_order(left: &InputSource, right: &InputSource) -> CmpOrdering {
    left.localized_name
        .to_lowercase()
        .cmp(&right.localized_name.to_lowercase())
        .then_with(|| left.localized_name.cmp(&right.localized_name))
        .then_with(|| left.identifier.cmp(&right.identifier))
}

fn discover_in_roots(roots: &[PathBuf]) -> Vec<CatalogItem> {
    let mut applications = Vec::new();
    let mut seen_paths = HashSet::new();

    for root in roots.iter().filter(|root| root.is_dir()) {
        let mut entries = WalkDir::new(root).follow_links(false).into_iter();
        while let Some(entry) = entries.next() {
            let entry = match entry {
                Ok(entry) => entry,
                Err(error) => {
                    tracing::warn!(
                        root = %root.display(),
                        error = %error,
                        "Could not inspect part of an application directory"
                    );
                    continue;
                }
            };
            let path = entry.path();
            if !is_application_bundle(path) {
                continue;
            }

            if entry.file_type().is_dir() {
                entries.skip_current_dir();
            }
            if !path.is_dir() || !seen_paths.insert(path.to_owned()) {
                continue;
            }

            applications.push(catalog_item_from_bundle(path));
        }
    }

    applications.sort_by(|left, right| {
        left.title
            .to_lowercase()
            .cmp(&right.title.to_lowercase())
            .then_with(|| left.id.cmp(&right.id))
    });
    applications
}

fn is_application_bundle(path: &Path) -> bool {
    path.extension()
        .and_then(|extension| extension.to_str())
        .is_some_and(|extension| extension.eq_ignore_ascii_case("app"))
}

fn catalog_item_from_bundle(bundle_path: &Path) -> CatalogItem {
    let fallback_title = bundle_path
        .file_stem()
        .and_then(|name| name.to_str())
        .filter(|name| !name.trim().is_empty())
        .unwrap_or("Application")
        .to_owned();
    let info_path = bundle_path.join("Contents/Info.plist");
    let dictionary = match Value::from_file(&info_path) {
        Ok(Value::Dictionary(dictionary)) => Some(dictionary),
        Ok(_) => {
            tracing::debug!(
                path = %info_path.display(),
                "Application Info.plist was not a dictionary"
            );
            None
        }
        Err(error) => {
            tracing::debug!(
                path = %info_path.display(),
                error = %error,
                "Using the bundle name because Info.plist could not be read"
            );
            None
        }
    };

    let display_name = dictionary
        .as_ref()
        .and_then(|dictionary| nonempty_string(dictionary, "CFBundleDisplayName"))
        .or_else(|| {
            dictionary
                .as_ref()
                .and_then(|dictionary| nonempty_string(dictionary, "CFBundleName"))
        })
        .unwrap_or_else(|| fallback_title.clone());
    let icon_path = application_icon_path(bundle_path, dictionary.as_ref());

    let mut item = CatalogItem::application(bundle_path, display_name);
    item.icon_path = icon_path;
    if let Some(dictionary) = dictionary {
        for key in ["CFBundleName", "CFBundleIdentifier"] {
            if let Some(keyword) = nonempty_string(&dictionary, key)
                && !item
                    .keywords
                    .iter()
                    .any(|existing| existing.eq_ignore_ascii_case(&keyword))
                && !item.title.eq_ignore_ascii_case(&keyword)
            {
                item.keywords.push(keyword);
            }
        }
    }
    item
}

fn application_icon_path(bundle_path: &Path, dictionary: Option<&Dictionary>) -> Option<PathBuf> {
    let resources = bundle_path.join("Contents/Resources");
    if !fs::symlink_metadata(&resources).is_ok_and(|metadata| metadata.file_type().is_dir()) {
        return None;
    }
    let canonical_resources = fs::canonicalize(&resources).ok()?;

    if let Some(dictionary) = dictionary {
        for candidate in icon_file_candidates(dictionary) {
            if let Some(path) = resolve_icon_candidate(&resources, &canonical_resources, candidate)
            {
                return Some(path);
            }
        }
    }

    fallback_icon_path(&resources)
}

fn icon_file_candidates(dictionary: &Dictionary) -> Vec<&str> {
    let mut candidates = Vec::new();
    append_icon_file_value(dictionary.get("CFBundleIconFile"), &mut candidates);

    let primary_icon = dictionary
        .get("CFBundleIcons")
        .and_then(Value::as_dictionary)
        .and_then(|icons| icons.get("CFBundlePrimaryIcon"))
        .and_then(Value::as_dictionary);
    if let Some(primary_icon) = primary_icon {
        append_icon_file_value(primary_icon.get("CFBundleIconFiles"), &mut candidates);
    }

    append_icon_file_value(dictionary.get("CFBundleIconFiles"), &mut candidates);
    candidates
}

fn append_icon_file_value<'a>(value: Option<&'a Value>, candidates: &mut Vec<&'a str>) {
    let Some(value) = value else {
        return;
    };

    if let Some(candidate) = value.as_string() {
        candidates.push(candidate);
    } else if let Some(values) = value.as_array() {
        candidates.extend(values.iter().filter_map(Value::as_string));
    }
}

fn resolve_icon_candidate(
    resources: &Path,
    canonical_resources: &Path,
    candidate: &str,
) -> Option<PathBuf> {
    let candidate = candidate.trim();
    if candidate.is_empty() {
        return None;
    }

    let relative = Path::new(candidate);
    if relative.is_absolute()
        || !relative
            .components()
            .all(|component| matches!(component, Component::Normal(_)))
    {
        return None;
    }

    let mut relative = relative.to_owned();
    if !relative
        .extension()
        .and_then(|extension| extension.to_str())
        .is_some_and(|extension| extension.eq_ignore_ascii_case("icns"))
    {
        let mut file_name = relative.file_name()?.to_os_string();
        file_name.push(".icns");
        relative.set_file_name(file_name);
    }

    let path = resources.join(relative);
    if !fs::symlink_metadata(&path).is_ok_and(|metadata| metadata.file_type().is_file()) {
        return None;
    }
    let canonical_path = fs::canonicalize(&path).ok()?;
    canonical_path
        .starts_with(canonical_resources)
        .then_some(path)
}

fn fallback_icon_path(resources: &Path) -> Option<PathBuf> {
    let mut icons = fs::read_dir(resources)
        .ok()?
        .filter_map(|entry| entry.ok())
        .filter_map(|entry| {
            let path = entry.path();
            let is_icns = path
                .extension()
                .and_then(|extension| extension.to_str())
                .is_some_and(|extension| extension.eq_ignore_ascii_case("icns"));
            (is_icns && entry.file_type().is_ok_and(|file_type| file_type.is_file()))
                .then_some(path)
        })
        .collect::<Vec<_>>();
    icons.sort();
    icons.into_iter().next()
}

fn nonempty_string(dictionary: &Dictionary, key: &str) -> Option<String> {
    dictionary
        .get(key)
        .and_then(Value::as_string)
        .map(str::trim)
        .filter(|value| !value.is_empty())
        .map(str::to_owned)
}

fn launch_agent_path() -> Option<PathBuf> {
    UserDirs::new().map(|directories| {
        directories
            .home_dir()
            .join("Library/LaunchAgents")
            .join(LAUNCH_AGENT_FILE_NAME)
    })
}

fn launch_at_login_enabled_at(path: &Path, executable: &Path) -> bool {
    let Ok(Value::Dictionary(dictionary)) = Value::from_file(path) else {
        return false;
    };

    let label_matches = dictionary
        .get("Label")
        .and_then(Value::as_string)
        .is_some_and(|label| label == LAUNCH_AGENT_LABEL);
    let run_at_load = dictionary
        .get("RunAtLoad")
        .and_then(Value::as_boolean)
        .unwrap_or(false);
    let executable_matches = dictionary
        .get("ProgramArguments")
        .and_then(Value::as_array)
        .and_then(|arguments| arguments.first())
        .and_then(Value::as_string)
        .is_some_and(|configured| Path::new(configured) == executable);
    let starts_hidden = dictionary
        .get("ProgramArguments")
        .and_then(Value::as_array)
        .and_then(|arguments| arguments.get(1))
        .and_then(Value::as_string)
        .is_some_and(|argument| argument == START_HIDDEN_ARGUMENT);

    label_matches && run_at_load && executable_matches && starts_hidden
}

fn write_launch_agent(path: &Path, executable: &Path) -> Result<()> {
    let parent = path
        .parent()
        .filter(|parent| !parent.as_os_str().is_empty())
        .ok_or_else(|| PlatformError::Io {
            operation: "locating the LaunchAgents directory",
            path: path.to_owned(),
            source: io::Error::new(io::ErrorKind::InvalidInput, "path has no parent"),
        })?;
    fs::create_dir_all(parent).map_err(|source| PlatformError::Io {
        operation: "creating the LaunchAgents directory",
        path: parent.to_owned(),
        source,
    })?;

    let mut dictionary = Dictionary::new();
    dictionary.insert(
        "Label".to_owned(),
        Value::String(LAUNCH_AGENT_LABEL.to_owned()),
    );
    dictionary.insert(
        "ProgramArguments".to_owned(),
        Value::Array(vec![
            Value::String(
                executable
                    .to_str()
                    .ok_or_else(|| PlatformError::InvalidExecutablePath(executable.to_owned()))?
                    .to_owned(),
            ),
            Value::String(START_HIDDEN_ARGUMENT.to_owned()),
        ]),
    );
    dictionary.insert("RunAtLoad".to_owned(), Value::Boolean(true));

    let mut encoded = Vec::new();
    Value::Dictionary(dictionary)
        .to_writer_xml(&mut encoded)
        .map_err(PlatformError::PlistSerialization)?;

    let (mut file, temp_path) = create_temporary_file(path)?;
    if let Err(source) = file.write_all(&encoded).and_then(|()| file.sync_all()) {
        let _ = fs::remove_file(&temp_path);
        return Err(PlatformError::Io {
            operation: "writing the launch-at-login property list",
            path: temp_path,
            source,
        });
    }
    drop(file);

    if let Err(source) = fs::rename(&temp_path, path) {
        let _ = fs::remove_file(&temp_path);
        return Err(PlatformError::Io {
            operation: "installing the launch-at-login property list",
            path: path.to_owned(),
            source,
        });
    }
    sync_directory(parent).map_err(|source| PlatformError::Io {
        operation: "synchronizing the LaunchAgents directory",
        path: parent.to_owned(),
        source,
    })
}

fn remove_launch_agent(path: &Path) -> Result<()> {
    match fs::remove_file(path) {
        Ok(()) => {}
        Err(source) if source.kind() == io::ErrorKind::NotFound => return Ok(()),
        Err(source) => {
            return Err(PlatformError::Io {
                operation: "removing the launch-at-login property list",
                path: path.to_owned(),
                source,
            });
        }
    }

    if let Some(parent) = path.parent() {
        sync_directory(parent).map_err(|source| PlatformError::Io {
            operation: "synchronizing the LaunchAgents directory",
            path: parent.to_owned(),
            source,
        })?;
    }
    Ok(())
}

fn create_temporary_file(target: &Path) -> Result<(File, PathBuf)> {
    let file_name = target.file_name().ok_or_else(|| PlatformError::Io {
        operation: "allocating a launch-at-login temporary file",
        path: target.to_owned(),
        source: io::Error::new(io::ErrorKind::InvalidInput, "path has no file name"),
    })?;

    for _ in 0..128 {
        let counter = TEMP_FILE_COUNTER.fetch_add(1, Ordering::Relaxed);
        let timestamp = SystemTime::now()
            .duration_since(UNIX_EPOCH)
            .map(|duration| duration.as_nanos())
            .unwrap_or(0);
        let mut name = file_name.to_os_string();
        name.push(format!(".tmp-{}-{timestamp}-{counter}", std::process::id()));
        let path = target.with_file_name(name);
        match OpenOptions::new().write(true).create_new(true).open(&path) {
            Ok(file) => return Ok((file, path)),
            Err(source) if source.kind() == io::ErrorKind::AlreadyExists => continue,
            Err(source) => {
                return Err(PlatformError::Io {
                    operation: "creating a launch-at-login temporary file",
                    path,
                    source,
                });
            }
        }
    }

    Err(PlatformError::Io {
        operation: "creating a launch-at-login temporary file",
        path: target.to_owned(),
        source: io::Error::new(
            io::ErrorKind::AlreadyExists,
            "could not allocate a unique temporary file",
        ),
    })
}

fn sync_directory(path: &Path) -> io::Result<()> {
    File::open(path)?.sync_all()
}

#[cfg(test)]
mod tests {
    use super::*;

    fn write_bundle(path: &Path, display_name: Option<&str>, bundle_name: &str) {
        fs::create_dir_all(path.join("Contents")).unwrap();
        let mut dictionary = Dictionary::new();
        if let Some(display_name) = display_name {
            dictionary.insert(
                "CFBundleDisplayName".to_owned(),
                Value::String(display_name.to_owned()),
            );
        }
        dictionary.insert(
            "CFBundleName".to_owned(),
            Value::String(bundle_name.to_owned()),
        );
        dictionary.insert(
            "CFBundleIdentifier".to_owned(),
            Value::String(format!("test.{bundle_name}")),
        );
        Value::Dictionary(dictionary)
            .to_file_xml(path.join("Contents/Info.plist"))
            .unwrap();
    }

    fn update_bundle_info(path: &Path, update: impl FnOnce(&mut Dictionary)) {
        let info_path = path.join("Contents/Info.plist");
        let Value::Dictionary(mut dictionary) = Value::from_file(&info_path).unwrap() else {
            panic!("bundle Info.plist must be a dictionary");
        };
        update(&mut dictionary);
        Value::Dictionary(dictionary)
            .to_file_xml(info_path)
            .unwrap();
    }

    fn write_icon(bundle: &Path, relative_path: &str) -> PathBuf {
        let path = bundle.join("Contents/Resources").join(relative_path);
        fs::create_dir_all(path.parent().unwrap()).unwrap();
        fs::write(&path, b"test icon").unwrap();
        path
    }

    #[test]
    fn discovery_reads_plist_and_never_descends_into_a_bundle() {
        let directory = tempfile::tempdir().unwrap();
        let applications = directory.path().join("Applications");
        let outer = applications.join("Outer.app");
        let nested = outer.join("Contents/Helpers/Nested.app");
        let utility = applications.join("Utilities/Utility.app");
        write_bundle(&outer, Some("Displayed Outer"), "Outer");
        write_bundle(&nested, Some("Must Not Appear"), "Nested");
        write_bundle(&utility, None, "Named Utility");

        let items = discover_in_roots(&[applications]);

        assert_eq!(items.len(), 2);
        assert!(items.iter().any(|item| item.title == "Displayed Outer"));
        assert!(items.iter().any(|item| item.title == "Named Utility"));
        assert!(!items.iter().any(|item| item.title == "Must Not Appear"));
    }

    #[test]
    fn application_roots_include_user_facing_core_services() {
        let roots = application_roots(Some(Path::new("/Users/example")));

        assert!(roots.contains(&PathBuf::from("/System/Library/CoreServices/Applications")));
        assert!(roots.contains(&PathBuf::from("/System/Library/CoreServices/Finder.app")));
        assert!(roots.contains(&PathBuf::from("/Users/example/Applications")));
    }

    #[test]
    fn discovery_resolves_bundle_icon_file_with_an_omitted_extension() {
        let directory = tempfile::tempdir().unwrap();
        let bundle = directory.path().join("Example.app");
        write_bundle(&bundle, Some("Example"), "Example");
        update_bundle_info(&bundle, |dictionary| {
            dictionary.insert(
                "CFBundleIconFile".to_owned(),
                Value::String("DuckIcon".to_owned()),
            );
        });
        let icon = write_icon(&bundle, "DuckIcon.icns");

        let item = catalog_item_from_bundle(&bundle);

        assert_eq!(item.icon_path.as_deref(), Some(icon.as_path()));
    }

    #[test]
    fn discovery_resolves_primary_and_legacy_icon_file_arrays() {
        let directory = tempfile::tempdir().unwrap();
        let primary_bundle = directory.path().join("Primary.app");
        write_bundle(&primary_bundle, None, "Primary");
        update_bundle_info(&primary_bundle, |dictionary| {
            let mut primary_icon = Dictionary::new();
            primary_icon.insert(
                "CFBundleIconFiles".to_owned(),
                Value::Array(vec![
                    Value::String("Missing".to_owned()),
                    Value::String("Icons/Primary.icns".to_owned()),
                ]),
            );
            let mut icons = Dictionary::new();
            icons.insert(
                "CFBundlePrimaryIcon".to_owned(),
                Value::Dictionary(primary_icon),
            );
            dictionary.insert("CFBundleIcons".to_owned(), Value::Dictionary(icons));
        });
        let primary_icon = write_icon(&primary_bundle, "Icons/Primary.icns");

        let legacy_bundle = directory.path().join("Legacy.app");
        write_bundle(&legacy_bundle, None, "Legacy");
        update_bundle_info(&legacy_bundle, |dictionary| {
            dictionary.insert(
                "CFBundleIconFiles".to_owned(),
                Value::Array(vec![Value::String("LegacyIcon".to_owned())]),
            );
        });
        let legacy_icon = write_icon(&legacy_bundle, "LegacyIcon.icns");

        assert_eq!(
            catalog_item_from_bundle(&primary_bundle)
                .icon_path
                .as_deref(),
            Some(primary_icon.as_path())
        );
        assert_eq!(
            catalog_item_from_bundle(&legacy_bundle)
                .icon_path
                .as_deref(),
            Some(legacy_icon.as_path())
        );
    }

    #[test]
    fn discovery_rejects_escaping_metadata_and_uses_a_deterministic_top_level_fallback() {
        let directory = tempfile::tempdir().unwrap();
        let bundle = directory.path().join("Fallback.app");
        write_bundle(&bundle, None, "Fallback");
        update_bundle_info(&bundle, |dictionary| {
            dictionary.insert(
                "CFBundleIconFile".to_owned(),
                Value::String("../OutsideIcon".to_owned()),
            );
        });
        write_icon(&bundle, "../OutsideIcon.icns");
        write_icon(&bundle, "Nested/Ignored.icns");
        write_icon(&bundle, "Zeta.icns");
        let expected = write_icon(&bundle, "Alpha.icns");

        let item = catalog_item_from_bundle(&bundle);

        assert_eq!(item.icon_path.as_deref(), Some(expected.as_path()));
    }

    #[test]
    fn launch_agent_is_valid_xml_with_required_fields() {
        let directory = tempfile::tempdir().unwrap();
        let path = directory.path().join(LAUNCH_AGENT_FILE_NAME);
        let executable = Path::new("/Applications/DuckGooKey.app/Contents/MacOS/DuckGooKey");

        write_launch_agent(&path, executable).unwrap();

        assert!(launch_at_login_enabled_at(&path, executable));
        let Value::Dictionary(dictionary) = Value::from_file(&path).unwrap() else {
            panic!("launch agent must be a dictionary");
        };
        assert_eq!(
            dictionary.get("Label").and_then(Value::as_string),
            Some(LAUNCH_AGENT_LABEL)
        );
        assert_eq!(
            dictionary.get("RunAtLoad").and_then(Value::as_boolean),
            Some(true)
        );
        assert_eq!(
            dictionary
                .get("ProgramArguments")
                .and_then(Value::as_array)
                .and_then(|arguments| arguments.first())
                .and_then(Value::as_string),
            Some(executable.to_str().unwrap())
        );
        assert_eq!(
            dictionary
                .get("ProgramArguments")
                .and_then(Value::as_array)
                .and_then(|arguments| arguments.get(1))
                .and_then(Value::as_string),
            Some(START_HIDDEN_ARGUMENT)
        );
    }

    #[test]
    fn disabling_login_launch_removes_only_the_exact_agent_file() {
        let directory = tempfile::tempdir().unwrap();
        let path = directory.path().join(LAUNCH_AGENT_FILE_NAME);
        let neighbor = directory.path().join("keep-me.plist");
        fs::write(&path, b"agent").unwrap();
        fs::write(&neighbor, b"neighbor").unwrap();

        remove_launch_agent(&path).unwrap();

        assert!(!path.exists());
        assert_eq!(fs::read(neighbor).unwrap(), b"neighbor");
        remove_launch_agent(&path).unwrap();
    }

    #[test]
    fn internal_actions_are_not_sent_to_open() {
        for action in [
            LaunchAction::CopyText {
                text: "example".to_owned(),
            },
            LaunchAction::SystemCommand {
                command: SystemCommand::OpenSystemSettings,
            },
            LaunchAction::EnterSearchMode {
                mode: crate::catalog::SearchMode::Files,
            },
            LaunchAction::ManageQuickLinks,
            LaunchAction::RefreshCatalog,
            LaunchAction::Quit,
        ] {
            assert!(matches!(
                launch(&action),
                Err(PlatformError::UnsupportedAction { .. })
            ));
        }
    }

    #[test]
    fn empty_spotlight_searches_do_not_start_a_process() {
        assert_eq!(search_files("   ", 10).unwrap(), Vec::<PathBuf>::new());
        assert_eq!(search_files("example", 0).unwrap(), Vec::<PathBuf>::new());
    }

    #[test]
    fn spotlight_query_cannot_be_interpreted_as_an_option() {
        assert_eq!(mdfind_name_query("notes"), "notes");
        assert_eq!(mdfind_name_query("-notes"), "*-notes");
        assert_eq!(mdfind_name_query("--help"), "*--help");
    }

    #[test]
    fn clipboard_history_ignores_confidential_and_transient_markers() {
        for data_type in IGNORED_PASTEBOARD_TYPES {
            assert!(is_ignored_pasteboard_type(data_type));
        }
        assert!(!is_ignored_pasteboard_type("public.utf8-plain-text"));
        assert!(!is_ignored_pasteboard_type("org.nspasteboard.source"));
    }

    #[test]
    fn system_commands_map_only_to_fixed_executables_and_arguments() {
        let cases = [
            (
                SystemCommand::OpenSystemSettings,
                OPEN_EXECUTABLE,
                &["-b", "com.apple.systempreferences"][..],
            ),
            (SystemCommand::Sleep, PMSET_EXECUTABLE, &["sleepnow"][..]),
            (
                SystemCommand::LockScreen,
                OSASCRIPT_EXECUTABLE,
                &[
                    "-e",
                    "tell application \"System Events\" to keystroke \"q\" using {control down, command down}",
                ][..],
            ),
            (
                SystemCommand::ToggleAppearance,
                OSASCRIPT_EXECUTABLE,
                &[
                    "-e",
                    "tell application \"System Events\" to tell appearance preferences to set dark mode to not dark mode",
                ][..],
            ),
            (
                SystemCommand::EmptyTrash,
                OSASCRIPT_EXECUTABLE,
                &["-e", "tell application \"Finder\" to empty trash"][..],
            ),
            (
                SystemCommand::LogOut,
                OSASCRIPT_EXECUTABLE,
                &["-e", "tell application \"System Events\" to log out"][..],
            ),
            (
                SystemCommand::Restart,
                OSASCRIPT_EXECUTABLE,
                &["-e", "tell application \"System Events\" to restart"][..],
            ),
            (
                SystemCommand::ShutDown,
                OSASCRIPT_EXECUTABLE,
                &["-e", "tell application \"System Events\" to shut down"][..],
            ),
        ];

        for (command, executable, arguments) in cases {
            let spec = system_command_spec(&command);
            assert_eq!(spec.executable, executable);
            assert_eq!(spec.arguments, arguments);
            assert!(!spec.operation.is_empty());
        }
    }

    #[test]
    fn spotlight_paths_are_nul_delimited_unicode_safe_and_capped() {
        let input =
            b"/Users/duck/My File.txt\0/Users/duck/\xed\x95\x9c\xea\xb8\x80.txt\0/ignored\0";

        let paths = read_nul_separated_paths(io::Cursor::new(input), 2).unwrap();

        assert_eq!(
            paths,
            vec![
                PathBuf::from("/Users/duck/My File.txt"),
                PathBuf::from("/Users/duck/한글.txt"),
            ]
        );
    }

    #[test]
    fn spotlight_parser_preserves_non_utf8_file_names() {
        let mut input = b"/Users/duck/".to_vec();
        input.push(0xff);
        input.extend_from_slice(b".txt\0");
        let expected = PathBuf::from(std::ffi::OsString::from_vec(
            b"/Users/duck/\xff.txt".to_vec(),
        ));

        let paths = read_nul_separated_paths(io::Cursor::new(input), 1).unwrap();

        assert_eq!(paths, vec![expected]);
    }

    #[test]
    fn input_sources_are_deduplicated_by_identifier_and_sorted_deterministically() {
        let input_sources = normalize_input_sources(vec![
            InputSource {
                identifier: "source.zulu".to_owned(),
                localized_name: "Zulu".to_owned(),
            },
            InputSource {
                identifier: "source.alpha".to_owned(),
                localized_name: "alpha".to_owned(),
            },
            InputSource {
                identifier: "source.zulu".to_owned(),
                localized_name: "zulu".to_owned(),
            },
            InputSource {
                identifier: "source.beta".to_owned(),
                localized_name: "Alpha".to_owned(),
            },
        ]);

        assert_eq!(
            input_sources,
            vec![
                InputSource {
                    identifier: "source.beta".to_owned(),
                    localized_name: "Alpha".to_owned(),
                },
                InputSource {
                    identifier: "source.alpha".to_owned(),
                    localized_name: "alpha".to_owned(),
                },
                InputSource {
                    identifier: "source.zulu".to_owned(),
                    localized_name: "Zulu".to_owned(),
                },
            ]
        );
    }
}
